name: 'GitHub Action Atmos Terraform Plan'
description: 'GitHub Action Atmos Terraform Plan'
author: hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  component:
    description: "The name of the component to plan."
    required: true
  stack:
    description: "The stack name for the given component."
    required: true
  component-path:
    description: "The path to the base component. Atmos defines this value as component_path."
    required: true
  terraform-plan-role:
    description: "The AWS role to be used to plan Terraform."
    required: true
  terraform-state-role:
    description: "The AWS role to be used to retrieve the planfile from AWS."
    required: true
  terraform-state-bucket:
    description: "The S3 Bucket where the planfiles are stored."
    required: true
  terraform-state-table:
    description: "The DynamoDB table where planfile metadata is stored."
    required: true
  aws-region:
    description: "AWS region for assuming identity."
    required: false
    default: "us-east-1"
  atmos-version:
    description: "Atmos version to use for vendoring. Default 'latest'"
    required: false
    default: 'latest'
  terraform-version:
    description: 'The version of Terraform CLI to install. Instead of full version string you can also specify constraint string starting with "<" (for example `<1.13.0`) to install the latest version satisfying the constraint. A value of `latest` will install the latest version of Terraform CLI. Defaults to `latest`.'
    default: 'latest'
    required: false
  enable-infracost:
    description: "Whether to enable infracost summary. Requires secret `secrets.INFRACOST_API_KEY` to be specified. Default: 'false"
    default: 'false'
    required: false
  infracost-api-key:
    description: "Infracost API key"
    required: false
  token:
    description:
      Used to pull node distributions for Atmos from Cloud Posse's GitHub repository. Since there's a default, this is typically
      not supplied by the user. When running this action on github.com, the default value is sufficient. When running on
      GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform-version }}

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - uses: cloudposse/github-action-setup-atmos@v1
      with:
        atmos-version: ${{ inputs.atmos-version }}
        token: ${{ inputs.token }}
        install-wrapper: false

    - name: Filter Atmos Settings Value
      uses: cloudposse/github-action-atmos-get-setting@0.2.0
      id: atmos-settings
      with:
        component: ${{ inputs.component }}
        stack: ${{ inputs.stack }}
        settings-path: github.actions_enabled

    - name: Check if Action is Enable
      id: settings
      shell: bash
      run: |
        if [[ "${{ steps.atmos-settings.outputs.value }}" == "true" ]]; then
          echo "actions_enabled=true" >> $GITHUB_OUTPUT
        else
          echo "actions_enabled=false" >> $GITHUB_OUTPUT
        fi

    # setup-tfcmt requires this PATH update when running on self-hosted (amazon linux)
    # https://github.com/shmokmt/actions-setup-tfcmt/blob/main/action.yml#L11C1-L12C1
    - name: Update path
      shell: bash
      run: |
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Setup tfcmt
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      uses: shmokmt/actions-setup-tfcmt@v2
      with:
        version: v4.4.1
    
    - name: Configure Plan AWS Credentials
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      uses: aws-actions/configure-aws-credentials@v2.2.0
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.terraform-plan-role }}
        role-session-name: "atmos-terraform-plan-gitops"
        mask-aws-account-id: "no"

    - name: Atmos Terraform Plan
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      id: atmos-plan
      shell: bash
      run: |
        PLAN_FILE=$(echo "${{ inputs.stack }}-${{ inputs.component }}-${{github.sha}}.planfile" | sed 's#/#_#g') 
        PLAN_FILE_PATH=$(pwd)
        ATMOS_BASE_PATH=$GITHUB_WORKSPACE atmos terraform plan ${{ inputs.component }} \
          --stack ${{ inputs.stack }} \
          -out=$PLAN_FILE_PATH/$PLAN_FILE
        echo "plan_file=$PLAN_FILE" >> $GITHUB_OUTPUT
        echo "plan_file_path=$PLAN_FILE_PATH" >> $GITHUB_OUTPUT

    - name: Configure State AWS Credentials
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      uses: aws-actions/configure-aws-credentials@v2.2.0
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.terraform-state-role }}
        role-session-name: "atmos-terraform-state-gitops"
        mask-aws-account-id: "no"

    - name: Store Plan
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      uses: cloudposse/github-action-terraform-plan-storage@1.6.2
      id: store-plan
      with:
        action: storePlan
        planPath: ${{ steps.atmos-plan.outputs.plan_file }}
        component: ${{ inputs.component }}
        stack: ${{ inputs.stack }}
        tableName: ${{ inputs.terraform-state-table }}
        bucketName: ${{ inputs.terraform-state-bucket }}

    - name: Store Lockfile
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      uses: cloudposse/github-action-terraform-plan-storage@1.6.2
      with:
        action: storePlan
        planPath: ${{ inputs.component-path}}/.terraform.lock.hcl
        component: ${{ inputs.component }}
        stack: "${{ inputs.stack }}-lockfile"
        tableName: ${{ inputs.terraform-state-table }}
        bucketName: ${{ inputs.terraform-state-bucket }}

    - name: Setup Infracost
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ inputs.infracost-api-key }}

    - name: Setup Infracost env vars
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        BASE_BRANCH_PATH="base-${{ github.sha }}"
        echo "BASE_BRANCH_PATH=$BASE_BRANCH_PATH" >> $GITHUB_ENV
        echo "BASE_BRANCH_COMPONENT_PATH=$BASE_BRANCH_PATH/${{ inputs.component-path }}" >> $GITHUB_ENV
        echo "VARS_FILE=${{ inputs.stack }}-${{ inputs.component }}.terraform.tfvars.json" >> $GITHUB_ENV

    - name: Checkout default branch for Infracost to use as baseline
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      uses: actions/checkout@v3
      with:
        ref: '${{ github.event.pull_request.base.ref }}'
        path: "${{ env.BASE_BRANCH_PATH }}"

    - name: Atmos Terraform Plan for Infracost default branch
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        ATMOS_BASE_PATH=$GITHUB_WORKSPACE/${{ env.BASE_BRANCH_PATH }} atmos terraform plan ${{ inputs.component }} \
          --stack ${{ inputs.stack }} \
          -input=false || true

    - name: Generate Infracost cost estimate baseline
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        if [[ ! -d "${{ env.BASE_BRANCH_COMPONENT_PATH }}" ]]; then
          mkdir -p ${{ env.BASE_BRANCH_COMPONENT_PATH }}
          echo "{}" > ${{ env.BASE_BRANCH_COMPONENT_PATH }}/${{ env.VARS_FILE }}
          NULL_RESOURCE=$(cat <<EOF
          resource "null_resource" "default" {
            provisioner "local-exec" {
              command = "echo 'Hello World'"
            }
          }
          EOF
          )
          echo "$NULL_RESOURCE" > "${{ env.BASE_BRANCH_COMPONENT_PATH }}/main.tf"
        elif [[ ! -f "${{ env.BASE_BRANCH_COMPONENT_PATH }}/${{ env.VARS_FILE }}" ]]; then
          echo "{}" > ${{ env.BASE_BRANCH_COMPONENT_PATH }}/${{ env.VARS_FILE }}
        fi

        infracost breakdown \
          --path=${{ env.BASE_BRANCH_COMPONENT_PATH }} \
          --terraform-var-file=${{ env.VARS_FILE }} \
          --format=json \
          --out-file=/tmp/infracost-baseline.json

    - name: Generate Infracost diff as text
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        infracost diff \
          --path=${{ inputs.component-path }}/ \
          --terraform-var-file=${{ env.VARS_FILE }} \
          --format=diff \
          --compare-to=/tmp/infracost-baseline.json \
          --out-file=/tmp/infracost.txt

    - name: Generate Infracost diff as json
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        infracost diff \
          --path=${{ inputs.component-path }}/ \
          --terraform-var-file=${{ env.VARS_FILE }} \
          --format=json \
          --compare-to=/tmp/infracost-baseline.json \
          --out-file=/tmp/infracost.json

    - if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        cat /tmp/infracost-baseline.json
        cat /tmp/infracost.txt
        cat /tmp/infracost.json

    - name: Post Plan
      if: ${{ fromJSON(steps.settings.outputs.actions_enabled) }}
      id: post-plan
      shell: bash
      run: |
        cd ${{ inputs.component-path }}
        tfcmt \
          --config "${{ github.action_path }}/config/atmos_github_summary.yaml" \
          -owner "${{ github.repository_owner }}" \
          -repo "${{ github.event.repository.name }}" \
          -pr "${{ github.event.number }}" \
          -var "target:${{ inputs.stack }}-${{ inputs.component }}" \
          -var "component:${{ inputs.component }}" \
          -var "stack:${{ inputs.stack }}" \
          -var "job:${{ github.job }}" \
          --output $GITHUB_STEP_SUMMARY \
          plan -- terraform show ${{ steps.atmos-plan.outputs.plan_file_path }}/${{ steps.atmos-plan.outputs.plan_file }}

    - if: ${{ fromJSON(steps.settings.outputs.actions_enabled) && inputs.enable-infracost == 'true' }}
      shell: bash
      run: |
        DIFF_TOTAL_MONTH_COST=$(cat /tmp/infracost.json | jq --raw-output .diffTotalMonthlyCost)
        DIFF_TOTAL_MONTH_COST_SUMMARY=""

        if (( DIFF_TOTAL_MONTH_COST == 0 )); then
            DIFF_TOTAL_MONTH_COST_SUMMARY="monthly cost will not change"
        elif (( DIFF_TOTAL_MONTH_COST > 0 )); then
            # Rounding the value to two decimal places
            DIFF_TOTAL_MONTH_COST_SUMMARY=$(printf "%.2f" $DIFF_TOTAL_MONTH_COST)
            DIFF_TOTAL_MONTH_COST_SUMMARY="monthly cost will increase by \$$DIFF_TOTAL_MONTH_COST_SUMMARY 📈"
        else
            # Rounding the value to two decimal places
            DIFF_TOTAL_MONTH_COST_SUMMARY=$(printf "%.2f" $DIFF_TOTAL_MONTH_COST)
            DIFF_TOTAL_MONTH_COST_SUMMARY="monthly cost will decrease by \$$DIFF_TOTAL_MONTH_COST_SUMMARY 📉"
        fi

        echo "<details><summary>💰 Infracost estimate: ${DIFF_TOTAL_MONTH_COST_SUMMARY}</summary>" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        cat /tmp/infracost.txt >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '</details>' >> $GITHUB_STEP_SUMMARY
