name: 'GitHub Action Atmos Terraform Plan'
description: 'GitHub Action Atmos Terraform Plan'
author: hello@cloudposse.com
branding:
  icon: 'server'
  color: 'white'
inputs:
  component:
    description: "The name of the component to plan."
    required: true
  stack:
    description: "The stack name for the given component."
    required: true
  sha:
    description: "Commit SHA to plan. Default: github.sha"
    required: true
    default: "${{ github.event.pull_request.head.sha }}"
  drift-detection-mode-enabled:
    description: "Indicate whether this action is used in drift detection workflow."
    required: true
    default: 'false'
  atmos-pro-base-url:
    description: The base URL of Atmos Pro
    required: false
    default: "https://atmos-pro.com"    
  atmos-pro-upload-status:
    description: "If set atmos will upload the plan result to the pro API"
    required: false
    default: 'false'
  atmos-version:
    description: The version of atmos to install
    required: false
    default: ">= 1.158.0"
  atmos-config-path:
    description: The path to the atmos.yaml file
    required: true
  infracost-api-key:
    description: "Infracost API key"
    required: false
  metadata-retention-days:
    description: "Infracost API key"
    required: false
    default: "1"
  branding-logo-image:
    description: "Branding logo image url"
    required: false
    default: "https://cloudposse.com/logo-300x69.svg"
  branding-logo-url:
    description: "Branding logo url"
    required: false
    default: "https://cloudposse.com/"
  debug:
    description: "Enable action debug mode. Default: 'false'"
    default: 'false'
    required: false
  token:
    description:
      Used to pull node distributions for Atmos from Cloud Posse's GitHub repository. Since there's a default, this is typically
      not supplied by the user. When running this action on github.com, the default value is sufficient. When running on
      GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}
  skip-checkout:
    description: "Disable actions/checkout. Useful for when the checkout happens in a previous step and file are modified outside of git through other actions"
    required: false
    default: 'false'
  pr-comment:
    description: "Set to 'true' to create a PR comment with the summary of the plan"
    required: false
    default: 'false'
  plan-storage:
    description: "Enable plan storage. Default: 'true'. Set to 'false' to disable plan storage."
    required: false
    default: 'true'
  identity:
    description: Atmos auth identity
    required: false
    default: ""
outputs:
  summary:
    description: "Summary"
    value: "${{ steps.atmos-plan.outputs.result }}"
  plan_file:
    description: "Path to the terraform plan file"
    value: "${{ steps.atmos-plan.outputs.plan_file }}"
  plan_json:
    description: "Path to the terraform plan in JSON format"
    value: "${{ steps.atmos-plan.outputs.plan_file_json }}"
  has-changes:
    description: "Whether the plan has changes. Value is string 'true' or 'false'"
    value: "${{ steps.atmos-plan.outputs.changes }}"


runs:
  using: "composite"
  steps:
    - name: Checkout
      if: ${{ inputs.skip-checkout != 'true' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.sha }}

    - name: Set atmos cli config path vars
      shell: bash
      run: |-
        echo "ATMOS_CLI_CONFIG_PATH=$(realpath ${{ inputs.atmos-config-path }})" >> $GITHUB_ENV

    - name: Install Atmos
      if: ${{ inputs.atmos-version != '' }}
      uses: cloudposse/github-action-setup-atmos@v2
      with:
        # atmos-version: ${{ inputs.atmos-version }}
        atmos-version: v1.208.0-test.5
        token: ${{ inputs.token }}
        install-wrapper: false

    - name: Atmos Terraform Plan
      id: atmos-plan
      shell: bash
      env:
        ATMOS_PRO_BASE_URL: ${{ inputs.atmos-pro-base-url }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        atmos toolchain install hashicorp/terraform@1.14.5
        atmos toolchain install opentofu/opentofu@1.11.0
        eval "$(atmos toolchain env)"
        atmos terraform plan ${{ inputs.component }} \
        --stack ${{ inputs.stack }} \
        --logs-level=DEBUG \
        -lock=false \
        -input=false \
        -no-color
